jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - name: poetry setup
        run: poetry install --all-extras --with dev
      - name: Tests
        run: poetry run pytest
name: ci
on:
  push:
    branches:
      - "**"
  workflow_dispatch: null
permissions:
  actions: read
  contents: read
  id-token: write
